# _config.yml
title: Pocket Textbook Prototype
description: A 3-page demo of the Media & Society pocket textbook

# Use the Just the Docs theme (no plugins needed)
remote_theme: just-the-docs/just-the-doc

# Tell Jekyll where this will live on GitHub Pages:
url: "https://jxshualawrence.github.io"
baseurl: "/pocket-textbook-prototype"

# Treat docs/ as your site’s pages:
collections:
  docs:
    output: true